
name: Build and Release

permissions:
  packages: write
  contents: write

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

      
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    

    - name: Set RUSTMARKS_VERSION
      run: echo "RUSTMARKS_VERSION=$(git describe --abbrev=0 --tags)" | sed 's/v//g' >> $GITHUB_ENV


    - name: Build
      run: |
        make build-deb

    - name: Create version file
      run: echo ${{ env.RUSTMARKS_VERSION }} > ./target/deb/version

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: ${{ env.RUSTMARKS_VERSION }}
        tag_name: v${{ env.RUSTMARKS_VERSION }}
        draft: false
        prerelease: false
        body_path: ./docs/changes.md

    - name: Upload amd64 asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/rustmarks
        asset_name: rustmarks_${{ env.RUSTMARKS_VERSION }}_linux_amd64
        asset_content_type: application/octet-stream
  
    - name: Upload amd64 deb asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/deb/rustmarks_${{ env.RUSTMARKS_VERSION }}-1_amd64.deb
        asset_name: rustmarks_${{ env.RUSTMARKS_VERSION }}-1_amd64.deb
        asset_content_type: application/octet-stream

    - name: Deploy through ssh
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "./target/deb/*.deb"
        TARGET: "/home/${{ secrets.REMOTE_USER }}/rustmarks/build/deb/"

    - name: Copy version file
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "./target/deb/version"
        TARGET: "/home/${{ secrets.REMOTE_USER }}/rustmarks/build/deb/"

    - name: Update apt repository
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /home/${{ secrets.REMOTE_USER }}/rustmarks/scripts/update-apt-repo.sh